In [44]:
import numpy as np
import math

sgm = lambda x: 1/(1+np.exp(-x))
data1=[]
y_data=[]
for i in range(200):
    ar, y = np.random.randint(10, size=(3, 3)), 1    
    if i<=100: ar[2][0],ar[2][1],ar[2][2]=0,0,0;ar[1][0],ar[1][1],ar[1][2]=1,1,1; y=0
    data1.append(ar)
    y_data.append(y)
y = np.array([y_data])
train_set_x_orig=np.array(data1)
anorm=np.linalg.norm(y)
x = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T/anorm
m = train_set_x_orig.shape[0]
print(train_set_x_orig.shape, m, y.shape, x.shape)
w,b=np.zeros((x.shape[0],1)),float(0)
learning_rate=0.05

(200, 3, 3) 200 (1, 200) (9, 200)


In [45]:
y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1]])

In [46]:
x

array([[0.        , 0.50251891, 0.20100756, ..., 0.70352647, 0.50251891,
        0.10050378],
       [0.30151134, 0.90453403, 0.10050378, ..., 0.        , 0.50251891,
        0.90453403],
       [0.80403025, 0.20100756, 0.20100756, ..., 0.        , 0.20100756,
        0.40201513],
       ...,
       [0.        , 0.        , 0.        , ..., 0.10050378, 0.40201513,
        0.60302269],
       [0.        , 0.        , 0.        , ..., 0.80403025, 0.90453403,
        0.10050378],
       [0.        , 0.        , 0.        , ..., 0.60302269, 0.10050378,
        0.50251891]])

In [47]:
w

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [48]:
a=np.dot(w.T,x)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]])

In [49]:
for i in range(100000):
    a=sgm(np.dot(w.T,x)+b)
    dz=np.subtract(a, y)/m
    dw=np.dot(x, dz.T)/m
    db=np.sum(a - y)/m
    w = w - dw * learning_rate
    b = b - db * learning_rate
    cost= -1/m*np.sum(y*np.log(a)+ (1-y)*np.log(1-a))  
    if i%1000==0: print("{0:5} {1:8.4f} {2:8.4f} cost:{3:8.4f}".format(i, np.sum(np.log(a)), np.sum((1-y)*np.log(1-a)), cost))


    0 -138.6294 -70.0079 cost:  0.6931
 1000 -140.3840 -67.6337 cost:  0.6779
 2000 -140.4690 -66.1699 cost:  0.6632
 3000 -140.6031 -64.7542 cost:  0.6490
 4000 -140.7828 -63.3852 cost:  0.6354
 5000 -141.0050 -62.0615 cost:  0.6222
 6000 -141.2665 -60.7815 cost:  0.6094
 7000 -141.5644 -59.5440 cost:  0.5971
 8000 -141.8962 -58.3474 cost:  0.5852
 9000 -142.2591 -57.1903 cost:  0.5738
10000 -142.6508 -56.0714 cost:  0.5627
11000 -143.0691 -54.9894 cost:  0.5520
12000 -143.5117 -53.9427 cost:  0.5416
13000 -143.9767 -52.9303 cost:  0.5316
14000 -144.4623 -51.9507 cost:  0.5220
15000 -144.9667 -51.0027 cost:  0.5126
16000 -145.4883 -50.0853 cost:  0.5036
17000 -146.0256 -49.1970 cost:  0.4948
18000 -146.5772 -48.3370 cost:  0.4863
19000 -147.1417 -47.5040 cost:  0.4781
20000 -147.7180 -46.6970 cost:  0.4702
21000 -148.3049 -45.9150 cost:  0.4625
22000 -148.9014 -45.1571 cost:  0.4550
23000 -149.5065 -44.4223 cost:  0.4478
24000 -150.1193 -43.7096 cost:  0.4408
25000 -150.7389 -43.0183 

In [43]:
for i in range(m):
    a=sgm(np.dot(w.T,x.T[i])+b)
    print(i, x.T[i]*anorm, a, y[0][i], 1 if a>=.5 else 0 )

0 [2. 5. 0. 1. 1. 1. 0. 0. 0.] [0.17400718] 0 0
1 [8. 5. 6. 1. 1. 1. 0. 0. 0.] [0.16841684] 0 0
2 [1. 3. 0. 1. 1. 1. 0. 0. 0.] [0.17423441] 0 0
3 [2. 3. 6. 1. 1. 1. 0. 0. 0.] [0.17384466] 0 0
4 [1. 7. 0. 1. 1. 1. 0. 0. 0.] [0.17589738] 0 0
5 [6. 2. 1. 1. 1. 1. 0. 0. 0.] [0.1687229] 0 0
6 [1. 3. 8. 1. 1. 1. 0. 0. 0.] [0.1751237] 0 0
7 [5. 4. 7. 1. 1. 1. 0. 0. 0.] [0.17122306] 0 0
8 [5. 6. 5. 1. 1. 1. 0. 0. 0.] [0.17182208] 0 0
9 [8. 3. 6. 1. 1. 1. 0. 0. 0.] [0.16761202] 0 0
10 [6. 4. 2. 1. 1. 1. 0. 0. 0.] [0.16964055] 0 0
11 [7. 8. 8. 1. 1. 1. 0. 0. 0.] [0.17088428] 0 0
12 [6. 9. 9. 1. 1. 1. 0. 0. 0.] [0.17244666] 0 0
13 [3. 8. 3. 1. 1. 1. 0. 0. 0.] [0.17452691] 0 0
14 [1. 3. 9. 1. 1. 1. 0. 0. 0.] [0.17523511] 0 0
15 [5. 3. 2. 1. 1. 1. 0. 0. 0.] [0.17026957] 0 0
16 [7. 5. 0. 1. 1. 1. 0. 0. 0.] [0.1687969] 0 0
17 [2. 4. 3. 1. 1. 1. 0. 0. 0.] [0.17392591] 0 0
18 [7. 6. 1. 1. 1. 1. 0. 0. 0.] [0.16930961] 0 0
19 [0. 3. 6. 1. 1. 1. 0. 0. 0.] [0.17596248] 0 0
20 [2. 2. 3. 1. 1. 1. 0. 0. 0.] [